# Generated by Django 4.2.3 on 2023-12-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderplace_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
