# Generated by Django 4.2.3 on 2023-12-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_orderplace_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
